import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';
import GSAPProvider from './components/GSAPProvider';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} font-sans antialiased relative overflow-x-hidden`}
      >
        <GSAPProvider>
          {/* Dashed lines */}
          <div className="w-full h-full absolute left-0 top-0 z-0 max-sm:hidden pointer-events-none">
            <div className="dashed-line"></div>
            <div className="dashed-line"></div>
          </div>

          <div className="min-h-screen flex flex-col">
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </GSAPProvider>
      </body>
    </html>
  );
}
